application: ###APPID###
version: 1

runtime: python27
threadsafe: no
api_version: 1

inbound_services:
- warmup

builtins:
- remote_api: on
- deferred: on

libraries:
- name: django
  version: 1.3
- name: webapp2
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'simian.settings'


handlers:

### Warmup URL

- url: /_ah/warmup
  script: simian.mac.urls.app
  login: admin
  secure: always

### Dev Admin Console

#- url: /ahadmin/.*
#  script: $PYTHON_LIB/google/appengine/ext/admin
# login: admin
#  secure: always

### URLs commonly requested by Munki clients

- url: /pkgs/.*
  script: simian.mac.urls.app
  secure: always

- url: /pkgsinfo/.*
  script: simian.mac.urls.app
  secure: always

- url: /catalogs/.*
  script: simian.mac.urls.app
  secure: always

- url: /manifests/.*
  script: simian.mac.urls.app
  secure: always

- url: /deletepkg
  script: simian.mac.urls.app
  secure: always

- url: /reports
  script: simian.mac.urls.app
  secure: always

- url: /client_resources
  static_dir: client_resources
  secure: always

- url: /icons
  static_dir: icons
  secure: always
### Apple SUS integration, client repair, Munki log uploads, etc.

- url: /applesus/.*
  script: simian.mac.urls.app
  secure: always

- url: /repair
  script: simian.mac.urls.app
  secure: always

- url: /uploadfile/.*
  script: simian.mac.urls.app
  secure: always

- url: /uploadpkg
  script: simian.mac.urls.app
  # intentionally omit "secure: always" for Scotty/Blobstore functionality.

- url: /auth
  script: simian.mac.urls.app
  secure: always

- url: /uauth
  script: simian.mac.urls.app
  login: required
  secure: always

- url: /api/.*
  script: simian.mac.api.urls.app
  secure: always

### Cron Job Handler

- url: /cron/.*
  script: simian.mac.cron.main.app
  login: admin
  secure: always

### Static content for admin UI

- url: /admin/static
  static_dir: simian/mac/admin/static
  secure: always
  login: required

- url: /.*/admin/css
  static_dir: simian/mac/admin/css
  secure: always
  login: required

- url: /.*/admin/js
  static_dir: simian/mac/admin/js
  secure: always
  login: required

### Admin UI

- url: /admin($|/.*)
  script: simian.mac.admin.main.app
  secure: always
  login: required

### Catchall handler

- url: /.*
  script: simian.mac.urls.app
  secure: always
  login: required
