application: ###APPID###
version: 1
runtime: python
api_version: 1
inbound_services:
- warmup
builtins:
- remote_api: on


handlers:

### Warmup URL

- url: /_ah/warmup
  script: main.py
  login: admin
  secure: always


### Dev Admin Console

- url: /ahadmin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always

### URLs commonly requested by Munki clients

- url: /pkgs/.*
  script: main.py
  secure: always

- url: /pkgsinfo/.*
  script: main.py
  secure: always

- url: /catalogs/.*
  script: main.py
  secure: always

- url: /manifests/.*
  script: main.py
  secure: always

- url: /deletepkg
  script: main.py
  secure: always

- url: /reports
  script: main.py
  secure: always

### Apple SUS integration, client repair, Munki log uploads, etc.

- url: /applesus/.*
  script: main.py
  secure: always

- url: /repair
  script: main.py
  secure: always

- url: /uploadfile/.*
  script: main.py
  secure: always

- url: /uploadpkg
  script: main.py
  # intentionally omit "secure: always" for Scotty/Blobstore functionality.

- url: /auth
  script: main.py
  secure: always

- url: /uauth
  script: main.py
  login: required
  secure: always

- url: /loginz
  script: main.py
  secure: always
  # intentionally omit "login: required" for arriving loginz requests


- url: /api/.*
  script: main.py
  secure: always

### Deferred Tasks

- url: /_ah/queue/deferred
  script: simian/mac/deferred_wrapper.py
  secure: always
  login: admin

### Cron Job Handler

- url: /cron/.*
  script: simian/mac/cron/main.py
  login: admin
  secure: always

### Static content for admin UI

- url: /admin/static
  static_dir: simian/mac/admin/static
  secure: always
  login: required

- url: /.*/admin/css
  static_dir: simian/mac/admin/css
  secure: always
  login: required

- url: /.*/admin/js
  static_dir: simian/mac/admin/js
  secure: always
  login: required

### Admin UI

- url: /admin($|/.*)
  script: simian/mac/admin/main.py
  secure: always
  login: required

### Catchall handler

- url: /.*
  script: main.py
  secure: always
  login: required
